site_name: Vira Ivanova
nav:
  - Overview: Vira_general.md
  - Education: about.md
  - Skills: skills.md
  - 'Work Experience':
    - Experience: work experience.md
    - Selcted Past Work: page-two.md
  

theme:
  name: material      
  logo: images/wizeline_isotype.png
    
extra_css:
  - css/extra.css